#
# Conditional issue creation on broken build, powered by imjohnbo/issue-bot
#
name: Continuous Integration
on:
  [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Test
      id: test
      run: |
        echo "...these are some test steps..."

    - name: issue-bot
      if: failure()
      uses: imjohnbo/issue-bot@v3
      with:
        assignees: "handles, of, my, teammates"    # GitHub handles without the @
        labels: ci
        pinned: false
        close-previous: false
        title: Test failure
        body: "...yo {{ assignees }}, some error messages related to the broken test..."