on:
  push:
    branches:
    - main
  pull_request:

name: Continuous Integration

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - run: npm install

    - run: npm run build
        
    - run: npm run lint

    - run: npm run test
    
    - name: Commit changes to dist
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:main
