on:
  push:
    branches:
    - master
  pull_request:

name: Continuous Integration

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - run: npm install

    - run: npm run build
        
    - run: npm run lint

    - run: npm run test

    - name: Commit
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:master